Add reverse web socket proxy implementation
TooTallNate/Java-WebSocket pull request #1150
Opened 2021-05-15 20:55 UTC by nvazquez

## Description
Reverse web socket proxy implementation\

````
                       -----------------------------
    WS CLIENT <---->  || serverSide - clientSide || <----> WS SERVER
                       -----------------------------
 ````

## Related Issue

## Motivation and Context

## How Has This Been Tested?
Tested against VMware 7

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-05-17 21:24 UTC, marci4 commented
Hey  @nvazquez,

first thank you for your pull request.

I have a few problems with your pull request:
- It is an example implementation for a specific protocol
- It would be part of the library for every user
- Certificates are simply ignored
- I cannot test the code every release

Could you tell me why you want to add this code to the library?
Is it not better suited to publish the example e.g. on gist?

Best regards,
Marcel

2021-05-17 21:24 UTC, marci4 requested changes
See previous comment

2021-05-18 12:52 UTC, nvazquez commented
Hi @marci4 thanks for your feedback, let me explain further:

I work on the Apache CloudStack project and was facing an issue which required to implement a solution in which I could connect two endpoints by a middle man, as a reverse proxy. In both ends, I needed the connection to use the websocket protocol and could not find a solution that solves that. However, after doing some research I found this library which solved the handshake and could extend the WS-TCP reverse proxy to WS-WS reverse proxy.

The reason I would like to contribute this solution is because we have added this library as a dependency to solve the specific issue, but extended it with the code on this PR. Ideally, for future releases we would like to simply invoke a library class instead of extending the library.

I agree that this implementation is very specific to the problem I needed to fix, but I'm open to hearing from you on how to extend it and making it available for general purpose

2021-05-19 15:45 UTC, marci4 commented
Hello @nvazquez,

thank you very much for clearing this up.

To be honest I do not see the benefit for everyone else in your contribution. Most if not all other users do not require this implementation.
Apart from this, this library cannot provide any possible use case someone has.
I think it is simply in the nature of external libraries that you have to extend them in your own codebase.

Best regards,
Marcel

2021-05-19 16:20 UTC, FilipsR commented
From what I understand, the code you've added doesn't depend on any package-private stuff from this library, so there is no reason to modify Java-WebSocket - you could simply put your classes in a separate project. So I'm not sure what's the benefit of putting it here.

2021-05-19 16:21 UTC, PhilipRoman commented
From what I understand, the code you've added doesn't depend on any package-private stuff from this library, so there is no reason to modify Java-WebSocket - you could simply put your classes in a separate project. So I'm not sure what's the benefit of putting it here.

2021-05-21 13:47 UTC, closed without merging